// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbwXsS9CvDw5RsoUDMTZg4Z5GqKtOAzbY',
    appId: '1:1055224199913:web:5b5ef256cb836640ab4e78',
    messagingSenderId: '1055224199913',
    projectId: 'flame4',
    authDomain: 'flame4.firebaseapp.com',
    databaseURL: 'https://flame4-default-rtdb.firebaseio.com',
    storageBucket: 'flame4.firebasestorage.app',
    measurementId: 'G-K9KRJT8TML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmVx__tolkOfhpSuX7aobchpCQXNMR-QY',
    appId: '1:1055224199913:android:eab2db5edc66f752ab4e78',
    messagingSenderId: '1055224199913',
    projectId: 'flame4',
    databaseURL: 'https://flame4-default-rtdb.firebaseio.com',
    storageBucket: 'flame4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTe3eXg_7AHO5GaIeGVPK2ixxqlSYLcVI',
    appId: '1:1055224199913:ios:b92fbd68751b8c27ab4e78',
    messagingSenderId: '1055224199913',
    projectId: 'flame4',
    databaseURL: 'https://flame4-default-rtdb.firebaseio.com',
    storageBucket: 'flame4.firebasestorage.app',
    iosClientId: '1055224199913-ts2r0tmcvuf4evbui7pg5ff7kps11l19.apps.googleusercontent.com',
    iosBundleId: 'com.example.flame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTe3eXg_7AHO5GaIeGVPK2ixxqlSYLcVI',
    appId: '1:1055224199913:ios:b92fbd68751b8c27ab4e78',
    messagingSenderId: '1055224199913',
    projectId: 'flame4',
    databaseURL: 'https://flame4-default-rtdb.firebaseio.com',
    storageBucket: 'flame4.firebasestorage.app',
    iosClientId: '1055224199913-ts2r0tmcvuf4evbui7pg5ff7kps11l19.apps.googleusercontent.com',
    iosBundleId: 'com.example.flame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbwXsS9CvDw5RsoUDMTZg4Z5GqKtOAzbY',
    appId: '1:1055224199913:web:d0a6ae3f6b6aad6bab4e78',
    messagingSenderId: '1055224199913',
    projectId: 'flame4',
    authDomain: 'flame4.firebaseapp.com',
    databaseURL: 'https://flame4-default-rtdb.firebaseio.com',
    storageBucket: 'flame4.firebasestorage.app',
    measurementId: 'G-WRLBGM6FHS',
  );

}